### ISSUE TITLE
memory leak 

### ISSUE THREAD

**Issue by dail** [mozilla/nunjucks#1021]

**Comment by fdintino** [comment]
Both of your examples are identical. Should I just replace `render` in the second example with `renderString`?

**Comment by dail** [comment]
Sorry，I have paste wrong code for renderString demo. I have update the issue,  Please check it again.

**Comment by fdintino** [comment]
What tool is reporting a memory leak? I just wrote a test to check for memory leaks in renderString and didn't see any heap differences from multiple calls.

**Comment by dail** [comment]
I start an HTTP server with Koa, and use AB to run load test. And check the memory usage by PM2.

**Comment by JackPu** [comment]
I met the same problem. Nunjucks render the template in server-side cause too many memory.

**Comment by ttonyh** [comment]
I think I am as well (in node/server-side). We're using renderString in multiple places and in some filters. A lot of retained strings, as follows, here's a truncated snippet from a memory heap comparison in "(string)" via ChromeDevTools, debugging node runtime:

```
 (function anonymous(
 ) {
 function root(env, context, frame, runtime, cb) {
 var lineno = null;
 var colno = null;
 var output = "";
 try {
 var parentTemplate = null;
 var t_1;
...
```

**Comment by ttonyh** [comment]
For a little more context, I seem to be hitting a "out-of-memory" crash just AFTER the following code in the Nunjucks module, while running a load test:

npm_modules/nunjucks/src/transformer.js
```
function convertStatements(ast) {
  return depthWalk(ast, function (node) {
```
the param "node" gets highlighted by the ChromeDevTools console. 

If it helps, here's the current stack at the breakpoint just BEFORE the out-of-memory crash:

```
    at eval (eval at <anonymous> (../node_modules/nunjucks/src/transformer.js:155:34), <anonymous>:1:9)
    at ../node_modules/nunjucks/src/transformer.js:155:34
    at walk (../node_modules/nunjucks/src/transformer.js:78:23)
    at depthWalk (../node_modules/nunjucks/src/transformer.js:82:10)
    at convertStatements (../node_modules/nunjucks/src/transformer.js:155:10)
    at cps (../node_modules/nunjucks/src/transformer.js:184:10)
    at Object.transform (../node_modules/nunjucks/src/transformer.js:188:10)
    at Object.compile (../node_modules/nunjucks/src/compiler.js:1443:27)
    at Template._compile (../node_modules/nunjucks/src/environment.js:614:29)
    at Template.compile (../node_modules/nunjucks/src/environment.js:604:12)
    at Template.render (../node_modules/nunjucks/src/environment.js:522:12)
    at Environment.renderString (../node_modules/nunjucks/src/environment.js:362:17)
    at Object.renderString (../node_modules/nunjucks/index.js:98:14)
    at Object.genCssJsTag (../libs/helpers/template-filters.js:235:29)
    at Array.map (<anonymous>)
    at Context.procCssJsRes (../libs/helpers/template-filters.js:134:38)
    at eval (eval at _compile (../node_modules/nunjucks/src/environment.js:615:18), <anonymous>:82:99)
    at b_footer (eval at _compile (../node_modules/nunjucks/src/environment.js:615:18), <anonymous>:179:1)
    at eval (eval at _compile (../node_modules/nunjucks/src/environment.js:615:18), <anonymous>:78:85)
    at b_main (eval at _compile (../node_modules/nunjucks/src/environment.js:615:18), <anonymous>:78:1)
    at eval (eval at _compile (../node_modules/nunjucks/src/environment.js:615:18), <anonymous>:74:83)
    at b_header (eval at _compile (../node_modules/nunjucks/src/environment.js:615:18), <anonymous>:65:1)
```

**Comment by edevil** [comment]
@ttonyh Do you also see the memory leak running @dail 's code?
