### ISSUE TITLE
Deployment not working using Nunjucks

### ISSUE THREAD

**Issue by simranprdxn** [mozilla/nunjucks#1073]
Hi Guys,

Please help, why this could be a problem? 

> nunjucks@3.1.0 postinstall /tmp/deployment/application/node_modules/nunjucks
> postinstall-build src

module.js:471
throw err;
^

Error: Cannot find module './index'
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/tmp/deployment/application/node_modules/.bin/postinstall-build:2:1)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)

**Comment by fdintino** [comment]
What command are you using to install?

**Comment by simranprdxn** [comment]
@fdintino : npm install

**Comment by fdintino** [comment]
A few things that might help me sort this out: 

- what version of npm are you using. Any chance you could upgrade it?
- If you're running `npm install` in a place that already has files, consider clearing out whatever you can before running it again. So, for instance, if `/tmp/deployment/application/node_modules` exists before you run the command, try deleting it first and starting from scratch.

**Comment by fdintino** [comment]
Also, putting the full npm install in a gist and posting that here might provide useful context.

**Comment by boccob** [comment]
I have the same issue. Can be easily reproduced with `npm install --no-bin-links` (node v9.2.1 and npm v5.6.0).

**Comment by Ryanmtate** [comment]
Hi @fdintino 

Ran into this issue today:

```
> nunjucks@3.1.1 postinstall 

node_modules/nunjucks
> node scripts/postinstall-build.js src

module.js:515
    throw err;
    ^

Error: Cannot find module 'node_modules/nunjucks/scripts/postinstall-build.js'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Function.Module.runMain (module.js:653:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by fdintino** [comment]
Sorry about that. I'll need to add some test coverage around npm packaging. Could you check once more to see whether the 3.1.2 release addresses your issues?

**Comment by fdintino** [comment]
I'm going to assume that this issue is resolved. Please feel free to reopen to let me know if it is still an issue.

**Comment by boccob** [comment]
Works fine for me. Thank you for the fix!
