### ISSUE TITLE
About the Number '0' using toFixed()

### ISSUE THREAD

**Issue by mingjiu** [mozilla/nunjucks#1086]
When I using:
`<div>{{aNumberWhichIsZero.toFixed(2)}}</div>`
log:

> { Template render error: (/home/hmj/xxxxxx/public/dist/html/xxx.html)
  Template render error: (/home/hmj/xxxxxx/public/dist/html/templates/xxx.html)
  Error: Unable to call `aNumberWhichIsZero["toFixed"]`, which is undefined or falsey
    at Object.exports.prettifyError (/home/hmj/xxxxxx/node_modules/nunjucks/src/lib.js:34:15)
    at /home/hmj/xxxxxx/node_modules/nunjucks/src/environment.js:489:31
    at eval (eval at _compile (/home/hmj/xxxxxx/node_modules/nunjucks/src/environment.js:568:24), <anonymous>:57:11)
    at /home/hmj/xxxxxx/node_modules/nunjucks/src/environment.js:497:25
    at new_cls.root [as rootRenderFunc] (eval at _compile (/home/hmj/xxxxxx/node_modules/nunjucks/src/environment.js:568:24), <anonymous>:132:3)
    at new_cls.render (/home/hmj/xxxxxx/node_modules/nunjucks/src/environment.js:482:15)
    at eval (eval at _compile (/home/hmj/xxxxxx/node_modules/nunjucks/src/environment.js:568:24), <anonymous>:56:10)
    at fn (/home/hmj/xxxxxx/node_modules/a-sync-waterfall/index.js:26:24)
    at /home/hmj/xxxxxx/node_modules/a-sync-waterfall/index.js:66:22
    at executeSync (/home/hmj/xxxxxx/node_modules/a-sync-waterfall/index.js:8:15)
    at /home/hmj/xxxxxx/node_modules/a-sync-waterfall/index.js:65:11
    at eval (eval at _compile (/home/hmj/xxxxxx/node_modules/nunjucks/src/environment.js:568:24), <anonymous>:52:1)
    at createTemplate (/home/hmj/xxxxxx/node_modules/nunjucks/src/environment.js:235:25)
    at handle (/home/hmj/xxxxxx/node_modules/nunjucks/src/environment.js:250:25)
    at /home/hmj/xxxxxx/node_modules/nunjucks/src/environment.js:264:21
    at next (/home/hmj/xxxxxx/node_modules/nunjucks/src/lib.js:207:13) name: 'Template render error' }

**Comment by mingjiu** [comment]
I have check it again. It works.
The number was come from our backend's data. 
Maybe last time the ZERO from backend is the STRING.
Thanks.
