### ISSUE TITLE
parseAggregate error address?

### ISSUE THREAD

**Issue by Spown** [mozilla/nunjucks#1087]
@3.1.2

So I have made an error somewhere, but the error doesn't tell me where. This is all I get.
```js
{
  message: "parseAggregate: expected comma after expression",
  name: "Template render error",
  stack: "Template render error: parseAggregate: expected comma after expression\
    at Object._prettifyError ([...]\node_modules\nunjucks\src\lib.js:35:11)\
    ..."
}
```
I can find it manually, no problem, but it would be much easier if knew at least roughly where...

Thank you.

**Comment by ArmorDarks** [comment]
Do you render your template with `env.render` or `env.renderString`?

**Comment by Spown** [comment]
env.render(path, ctx). And I tried both sync and async versions.

**Comment by ArmorDarks** [comment]
Can you show full stack?

The message is quite strange because if an error would happen during rendering, it has to contain line numbers and source. But in your case, it looks like a typo in your code, which happens before rendering even can begin.

**Comment by Spown** [comment]
I've already found it - it was ``{{t('some_key'', var)}}`` i.e. an extraneous quote mark. So you say, I don't get template address on syntax errors?

**Comment by ArmorDarks** [comment]
I'm not sure what you're doing differently, but you should get an address.

For some reason, you even get a different error.

For instance, with your example I'm receiving following error:

```
>> Template render error: (J:\Work\soma-app\source\templates\index.nj) [Line 17, Column 19]
>>   parseSignature: expected comma after expression
```

Note that it is `Template render error`, not `parseAggregate` error

**Comment by Spown** [comment]
Full stack:
```
 Template render error: parseAggregate: expected comma after expression
       at Object._prettifyError ([prj_root]\node_modules\nunjucks\src\lib.js:35:11)
       at Template.render ([prj_root]\node_modules\nunjucks\src\environment.js:526:21)
       at [prj_root]\node_modules\nunjucks\src\environment.js:350:27
       at createTemplate ([prj_root]\node_modules\nunjucks\src\environment.js:299:9)
       at handle ([prj_root]\node_modules\nunjucks\src\environment.js:311:11)
       at [prj_root]\node_modules\nunjucks\src\environment.js:323:9
       at next ([prj_root]\node_modules\nunjucks\src\lib.js:281:7)
       at Object.asyncIter ([prj_root]\node_modules\nunjucks\src\lib.js:287:3)
       at Environment.getTemplate ([prj_root]\node_modules\nunjucks\src\environment.js:305:9)
       at Environment.render ([prj_root]\node_modules\nunjucks\src\environment.js:344:10)
       at [prj_root]\pages\index.js:240:60
       at [prj_root]\node_modules\q\q.js:1249:26
       at _fulfilled ([prj_root]\node_modules\q\q.js:854:54)
       at Promise.then.Q.nextTick.self.promiseDispatch.done ([prj_root]\node_modules\q\q.js:883:30)
       at Promise.__dirname.Promise.promise.promiseDispatch ([prj_root]\node_modules\q\q.js:816:13)
       at [prj_root]\node_modules\q\q.js:570:49
       at runSingle ([prj_root]\node_modules\q\q.js:137:13)
       at flush ([prj_root]\node_modules\q\q.js:125:13)
       at process._tickCallback (internal/process/next_tick.js:150:11)
```
not sure how can it help

**Comment by fdintino** [comment]
I have a fix for this that I'll be pushing out shortly.
