### ISSUE TITLE
Get a "Cannot find module 'njk'" error

### ISSUE THREAD

**Issue by Grear-0** [mozilla/nunjucks#1134]
Hi there ! 

I'm pretty new to node.js devlopment as well as Express and Nunjucks, so, sorry by advance if my error seems obvious for you.
*****
Here is the complete error :

```
Error: Cannot find module 'njk'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at new View (C:\Users\grear-0\Documents\CooHub\node_modules\express\lib\view.js:81:14)
    at Function.render (C:\Users\grear-0\Documents\CooHub\node_modules\express\lib\application.js:570:12)
    at ServerResponse.render (C:\Users\grear-0\Documents\CooHub\node_modules\express\lib\response.js:1008:7)
    at C:\Users\grear-0\Documents\CooHub\app\routes.js:26:13
    at Layer.handle [as handle_request] (C:\Users\grear-0\Documents\CooHub\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\grear-0\Documents\CooHub\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\grear-0\Documents\CooHub\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\grear-0\Documents\CooHub\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\grear-0\Documents\CooHub\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\grear-0\Documents\CooHub\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\grear-0\Documents\CooHub\node_modules\express\lib\router\index.js:275:10)
    at SessionStrategy.strategy.pass (C:\Users\grear-0\Documents\CooHub\node_modules\passport\lib\middleware\authenticate.js:338:9)
```
The project uses [express-nunjucks](https://www.npmjs.com/package/express-nunjucks). Here is the Nunjucks's configuration :

```
//config/nunjucks.js
const path = require('path');
module.exports = function (app) {
    const expressNunjucks = require('express-nunjucks');

    /*Ici, nous déterminons si l'application est
    en developpement ou en production*/
    const isDev = app.get('env') === 'development';

    //Templates folder
    app.set('views', path.join(__dirname, '../app/views/'));

    /* création de l'environnement Nunjucks
       avec un chargeur asynchrone embarqué */
    const njk = expressNunjucks(app,{
        watch : isDev,
        noCache: isDev
    });
}
```
it is just like example on **express-nunjucks**'s npm page.

Then I call `require ('./config/nunjucks.js')(app);` right in my **server.js** where *app* is `express()` with some middlewares and configurations.

My routes are configured in different modules

*in app/routes.js*
```
    app.get('/login', function (req, res) {
        res.render('login.njk');
    });
```
*or in app/admin.js*
```
    //gestion de la requête de la racine de l'administration
    //par défaut nous affichons le premier élément de
    //l'admin menu
    app.get ('/admin?:page', function (req, res) {
        if (!req.query.page){
            res.redirect ('admin?page=manage-user')
        }else{
            res.render('administration/' + req.query.page + '.njk', {
                datas: data
            });
        }
    })
```
Things become interesting when i tried without **_.njk_** extension... Error becomes :

```
Error: Failed to lookup view "login" in views directory "C:\Users\grear-0\Documents\CooHub\app\views\"
    at Function.render (C:\Users\grear-0\Documents\CooHub\node_modules\express\lib\application.js:580:17)
    at ServerResponse.render (C:\Users\grear-0\Documents\CooHub\node_modules\express\lib\response.js:1008:7)
    at C:\Users\grear-0\Documents\CooHub\app\routes.js:26:13
    at Layer.handle [as handle_request] (C:\Users\grear-0\Documents\CooHub\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\grear-0\Documents\CooHub\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\grear-0\Documents\CooHub\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\grear-0\Documents\CooHub\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\grear-0\Documents\CooHub\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\grear-0\Documents\CooHub\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\grear-0\Documents\CooHub\node_modules\express\lib\router\index.js:275:10)
    at SessionStrategy.strategy.pass (C:\Users\grear-0\Documents\CooHub\node_modules\passport\lib\middleware\authenticate.js:338:9)
    at SessionStrategy.authenticate (C:\Users\grear-0\Documents\CooHub\node_modules\passport\lib\strategies\session.js:75:10)
    at attempt (C:\Users\grear-0\Documents\CooHub\node_modules\passport\lib\middleware\authenticate.js:361:16)
    at authenticate (C:\Users\grear-0\Documents\CooHub\node_modules\passport\lib\middleware\authenticate.js:362:7)
    at Layer.handle [as handle_request] (C:\Users\grear-0\Documents\CooHub\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\grear-0\Documents\CooHub\node_modules\express\lib\router\index.js:317:13)
```

Thanks by advance for your time :)

**Comment by Grear-0** [comment]
And here we go ! Obvious was the word... yes.
Just added `app.set('view engine', 'njk');` to **config/nunjucks.js** and voilà !

Sorry for that :)
