### ISSUE TITLE
Unhandled error in trim filter: "TypeError: Cannot read property 'replace' of null"

### ISSUE THREAD

**Issue by AndrewPashkin** [mozilla/nunjucks#1145]
# Description
I encountered a strange case when rendering of a valid template causes such error:
```
Template render error: (/project/test.html) [Line 29, Column 16]
  TypeError: Cannot read property 'replace' of null
    at Object._prettifyError (/project/node_modules/nunjucks/src/lib.js:36:11)
    at /project/node_modules/nunjucks/src/environment.js:545:19
    at Template.root [as rootRenderFunc] (eval at _compile (/project/node_modules/nunjucks/src/environment.js:616:18), <anonymous>:237:3)
    at Template.render (/project/node_modules/nunjucks/src/environment.js:538:10)
    at /project/node_modules/nunjucks/src/environment.js:348:27
    at createTemplate (/project/node_modules/nunjucks/src/environment.js:297:9)
    at handle (/project/node_modules/nunjucks/src/environment.js:309:11)
    at /project/node_modules/nunjucks/src/environment.js:321:9
    at next (/project/node_modules/nunjucks/src/lib.js:280:7)
    at Object.asyncIter (/project/node_modules/nunjucks/src/lib.js:286:3)
```

# Test case:
[test.tar.gz](https://github.com/mozilla/nunjucks/files/2349163/test.tar.gz)

# Versions
Node.js: v4.4.7
Nunjucks: 3.1.3

**Comment by edwardhorsford** [comment]
I think I just found this too.

I've come to rely / expect that Nunjucks filters are safe to use - if something is undefined, they'll just return empty strings. That doesn't seem to be the case with the `trim` filter, which crashes.
