### ISSUE TITLE
Template render erro

### ISSUE THREAD

**Issue by allanamedrado** [mozilla/nunjucks#1281]
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1336:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  

Template render error: (C:\ws\views\index.html) [Line 59, Column 33]
  expected name as lookup value, got }}
    at Object._prettifyError (C:\ws\node_modules\nunjucks\src\lib.js:36:11)
    at Template.render (C:\ws\node_modules\nunjucks\src\environment.js:536:21)
    at C:\ws\node_modules\nunjucks\src\environment.js:364:27
    at createTemplate (C:\ws\node_modules\nunjucks\src\environment.js:313:9)
    at handle (C:\ws\node_modules\nunjucks\src\environment.js:325:11)
    at C:\ws\node_modules\nunjucks\src\environment.js:337:9
    at next (C:\ws\node_modules\nunjucks\src\lib.js:280:7)
    at Object.asyncIter (C:\ws\node_modules\nunjucks\src\lib.js:286:3)
    at Environment.getTemplate (C:\ws\node_modules\nunjucks\src\environment.js:319:9)
    at Environment.render (C:\ws\node_modules\nunjucks\src\environment.js:358:10)

**Comment by fdintino** [comment]
it sounds like you have an error in your template. I would look at line 59 of index.html there. I suspect you have something like:

```jinja2
{{ set myvariable = }}
```

**Comment by fdintino** [comment]
I'm going to close this as resolved, as it doesn't sound like a bug in nunjucks itself.
