### ISSUE TITLE
Include ignore missing results in a generic error when using async loader

### ISSUE THREAD

**Issue by megakoresh** [mozilla/nunjucks#1286]
If you include a template using async loader (e.g. we use our own loader that gets templates from S3 with rest calls), it will throw

```
Template render error: (cup/notification/ticket-resolved.txt)
  Error: src must be a string or an object describing the source
    at Object._prettifyError (/home/sddev/at-template/node_modules/nunjucks/src/lib.js:36:11)
    at /home/sddev/at-template/node_modules/nunjucks/src/environment.js:567:19
    at eval (eval at _compile (/home/sddev/at-template/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:41:11)
    at eval (eval at _compile (/home/sddev/at-template/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:21:11)
    at createTemplate (/home/sddev/at-template/node_modules/nunjucks/src/environment.js:295:11)
    at handle (/home/sddev/at-template/node_modules/nunjucks/src/environment.js:324:11)
    at /home/sddev/at-template/src/http_loader.ts:57:9
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  name: 'Template render error'
}
```

Template

```jinja
{%- ifAsync order.orderType %}
{% include "cup/notification/" + order.orderType | lower + "-resolved-details.txt" %}
{%- endif %}
```

If an expression `ifAsync` is replaced with `if` it simply doesn't work, as described in this [4 year old bug report](https://github.com/mozilla/nunjucks/issues/838#issuecomment-275674730)

**Comment by ogonkov** [comment]
Looks like custom loader is not follow [`getSource` method signature](https://mozilla.github.io/nunjucks/api.html#writing-a-loader). It should resolve callback with `{src: string, path: string}` object.

**Comment by megakoresh** [comment]
> Looks like custom loader is not follow [`getSource` method signature](https://mozilla.github.io/nunjucks/api.html#writing-a-loader). It should resolve callback with `{src: string, path: string}` object.

Yes sorry I did not update this issue. Changing getSource method signature and using ifAsync solves this problem. So a fix to this issue is in documentation, which, considering that ifAsync is not even documented, among other things, seems to be in a really bad state.

**Comment by ogonkov** [comment]
Am i right that you suggest to update this error message?

```
Error: src must be a string or an object describing the source
```
