### ISSUE TITLE
Async filters break when on the right-hand-side of a comparison operator

### ISSUE THREAD

**Issue by refactranthony** [mozilla/nunjucks#1340]
Here's a reproduction:

```
const nunjucks = require('nunjucks');

const env = new nunjucks.Environment();

//const expr = '{{ (4 | addone) == 5 }}'; // works
const expr = '{{ 5 == (4 | addone) }}'; // doesn't work
//const expr = '{{ 5 * (4 | addone) }}'; // works (!?)

env.addFilter('addone', (n, cb) => {
    cb(null, n + 1);
}, true);

nunjucks.compile(expr, env).render({}, (err, result) => {
    console.info('err: ', err);
    console.info('result: ', result);
});
```

Strangely, other operators like `*` and `+` seem to work fine. The same test with a sync filter also works.

**Comment by ogonkov** [comment]
Looks like filter got more than one argument in second case.

**Comment by refactranthony** [comment]
> Looks like filter got more than one argument in second case.

It actually gets only 1 argument: 

```
env.addFilter('addone', (...args) => {
    console.info('args: ', args);
    args[1](null, args[0] + 1);
}, true);

```

output:

```
args:  [ 4 ]
err:  Template render error: (unknown path)
  TypeError: args[1] is not a function
    at Object._prettifyError (/opt/tmp/nunjucks-test2/node_modules/nunjucks/src/lib.js:36:11)
    at /opt/tmp/nunjucks-test2/node_modules/nunjucks/src/environment.js:561:19
    at Template.root [as rootRenderFunc] (eval at _compile (/opt/tmp/nunjucks-test2/node_modules/nunjucks/src/environment.js:631:18), <anonymous>:17:3)
    at Template.render (/opt/tmp/nunjucks-test2/node_modules/nunjucks/src/environment.js:550:10)
    at Object.<anonymous> (/opt/tmp/nunjucks-test2/issue_repro.js:14:29)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1014:10) {
  name: 'Template render error'
}
```

Just saw your edit 👍

**Comment by ogonkov** [comment]
My guess that nunjucks failed to properly identify this fragment as filter, and mark it as asynchronous (??).
