### ISSUE TITLE
Template paths in errors when using renderString

### ISSUE THREAD

**Issue by kruncher** [mozilla/nunjucks#1359]
When using `renderString` it is possible to supply a path representing the template that is being rendered:

```js
nunjucksEnvironment.renderString(templateString, context, templatePath);
```

This works to the extend that the `templatePath` is output in error messages but any errors in other extended/included templates are also shown with `templatePath` instead of their actual paths.

How can those extended/included template paths also be shown?

**Comment by ogonkov** [comment]
Try `dev: true`, when creating your env

**Comment by kruncher** [comment]
@ogonkov this seems to show a JavaScript call stack rather than the templates themselves:

```
Error: tag name expected
    at new TemplateError (/Users/me/git/test/node_modules/nunjucks/src/lib.js:89:17)
    at Parser.error (/Users/me/git/test/node_modules/nunjucks/src/parser.js:84:12)
    at Parser.fail (/Users/me/git/test/node_modules/nunjucks/src/parser.js:88:16)
    at Parser.parseStatement (/Users/me/git/test/node_modules/nunjucks/src/parser.js:566:12)
    at Parser.parseNodes (/Users/me/git/test/node_modules/nunjucks/src/parser.js:1211:22)
    at Parser.parseAsRoot (/Users/me/git/test/node_modules/nunjucks/src/parser.js:1239:38)
    at Object.parse (/Users/me/git/test/node_modules/nunjucks/src/parser.js:1264:14)
    at Object.compile (/Users/me/git/test/node_modules/nunjucks/src/compiler.js:1445:44)
    at Template._compile (/Users/me/git/test/node_modules/nunjucks/src/environment.js:632:29)
    at Template.init (/Users/me/git/test/node_modules/nunjucks/src/environment.js:509:14)
```
