### ISSUE TITLE
No default engine error

### ISSUE THREAD

**Issue by mdtausifiqbal** [mozilla/nunjucks#1432]
### Please resolve this error
```
Error: No default engine was specified and no extension was provided.
    at new NunjucksView (H:\Projects\blog app\node_modules\nunjucks\src\express-app.js:13:13)
    at Function.render (H:\Projects\blog app\node_modules\express\lib\application.js:587:12)
    at ServerResponse.render (H:\Projects\blog app\node_modules\express\lib\response.js:1039:7)
    at H:\Projects\blog app\server.js:19:9
    at Layer.handle [as handle_request] (H:\Projects\blog app\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\Projects\blog app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (H:\Projects\blog app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (H:\Projects\blog app\node_modules\express\lib\router\layer.js:95:5)
    at H:\Projects\blog app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (H:\Projects\blog app\node_modules\express\lib\router\index.js:346:12)
```

**Comment by webketje** [comment]
As your stack trace indicates, this error is caused by a user misconfiguration in express (app.set('view engine')). This issue can be closed.
