### ISSUE TITLE
Customising syntax: using erb syntax causes errors

### ISSUE THREAD

**Issue by callumacrae** [mozilla/nunjucks#352]
```js
  var env = nunjucks.configure({
    tags: {
      blockStart: '{%',
      blockEnd: '%}',
      variableStart: '<%=',
      variableEnd: '%>'
    }
  });

  var context = {
    name: 'sarah'
  };

  var res = env.renderString('<%= name %>, context);
```

That outputs "sarah" as expected.

However, changing "blockStart" and "blockEnd" to `<%` and `%>` causes an error:

```
Template render error: (unknown path) [Line 1, Column 1]
  tag name expected
    at Object.exports.withPrettyErrors ([project]/node_modules/nunjucks/src/lib.js:33:17)
    at Obj.extend.render ([project]/node_modules/nunjucks/src/environment.js:344:20)
    at Obj.extend.renderString ([project]/node_modules/nunjucks/src/environment.js:231:21)
```

I'm guessing it's because blockEnd and variableEnd are the same. Is there a way around this?

**Comment by jlongster** [comment]
Yeah, sorry tag and variable names have to be different :( tags are quite different and the compiler is built on these syntax differences.
