### ISSUE TITLE
Conditional extends should work, no?

### ISSUE THREAD

**Issue by pennyfx** [mozilla/nunjucks#39]
I'm trying to return html fragments and figured that I could achieve this by conditionally setting a template to extend from.   The true case works, but the false case throws an exception.

```javascript
   it('should allow extends blocks inside of if blocks', function(){
        var s = render( '{% if true %}'+
                        '{% extends "base.html" %}'+
                        '{% endif %}'+
                        '{% block block1 %}fragment{% endblock %}');
        s.should.equal('FoofragmentBazFizzle');

        s = render( '{% if false %}'+
                    '{% extends "base.html" %}'+
                    '{% endif %}'+
                    '{% block block1 %}fragment{% endblock %}');
        s.should.equal('fragment');
    });
```

Error

```
TypeError: Cannot call method 'rootRenderFunc' of undefined
      at [object Object].root [as rootRenderFunc] (eval at <anonymous> (/Users/aschaar/programming/xtags-org/node_modules/nunjucks/src/environment.js:273:24))
      at [object Object].render (/Users/aschaar/programming/xtags-org/node_modules/nunjucks/src/environment.js:242:21)
      at render (/Users/aschaar/programming/xtags-org/node_modules/nunjucks/tests/util.js:9:14)
      at Context.<anonymous> (/Users/aschaar/programming/xtags-org/node_modules/nunjucks/tests/compiler.js:325:13)
      at Test.run (/Users/aschaar/programming/xtags-org/node_modules/nunjucks/node_modules/mocha/lib/runnable.js:213:32)
      at Runner.runTest (/Users/aschaar/programming/xtags-org/node_modules/nunjucks/node_modules/mocha/lib/runner.js:343:10)
      at /Users/aschaar/programming/xtags-org/node_modules/nunjucks/node_modules/mocha/lib/runner.js:389:12
      at next (/Users/aschaar/programming/xtags-org/node_modules/nunjucks/node_modules/mocha/lib/runner.js:269:14)
      at /Users/aschaar/programming/xtags-org/node_modules/nunjucks/node_modules/mocha/lib/runner.js:278:7
      at next (/Users/aschaar/programming/xtags-org/node_modules/nunjucks/node_modules/mocha/lib/runner.js:226:23)
      at Array.0 (/Users/aschaar/programming/xtags-org/node_modules/nunjucks/node_modules/mocha/lib/runner.js:246:5)
      at EventEmitter._tickCallback (node.js:192:40)
make: *** [test] Error 1

```

**Comment by jlongster** [comment]
This should work on master; will be released with 2.0.
