### ISSUE TITLE
Output from i18n library throwing errors in certain cases

### ISSUE THREAD

**Issue by KishCom** [mozilla/nunjucks#399]
I'm experiencing a very weird parse error with Nunjucks.

Libraries involved:
"nunjucks": "1.2.0"
"i18n": "0.5.0"
"express": "4.12.3"

App setup something like:

    var express = require("express"),
        nunjucks = require("nunjucks");
    var site = module.exports = express();
    nunjucks.configure('views', {
        autoescape: true,
        express: site
    });
    site.set("view engine", "html");
    site.set("views", __dirname + "/views");
    i18n.configure({
      locales: config.supportedLocales,
      cookie: "mysites_lang.sid",
      directory: __dirname + '/locales'
    });
    // Express helper (makes '__' functions available in templates)
    site.use(i18n.init);
    site.get("/", routes.index); /// etc - normal Express style Node app

In the template this works:

    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Example</title>
    </head>
    <body>
        
       {{ __('translate_me') }}
        <script type="text/ng-template" id="game.html">
            <h4>Some Angular Script</h4>
            {{ __('translate_me') }}
        </script>
    </body>
    </html>

However this throws a 500:

    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Example</title>
    </head>
    <body>
        
        <div data-somedata="{{ __('translate_me') }}"></div>
        
        <script type="text/ng-template" id="game.html">
            <h4>Some Angular Script</h4>
            
            <div data-somedata="{{ __('translate_me') }}"></div>
        </script>
    </body>
    </html>

Full trace:

    Template render error: TypeError: Cannot call method 'indexOf' of undefined
    at localeAccessor (/home/ubuntu/nunjucksapp/node_modules/i18n/i18n.js:462:29)
    at translate (/home/ubuntu/nunjucksapp/node_modules/i18n/i18n.js:428:18)
    at IncomingMessage.i18nTranslate (/home/ubuntu/nunjucksapp/node_modules/i18n/i18n.js:119:11)
    at Object.object.(anonymous function) (/home/ubuntu/nunjucksapp/node_modules/i18n/i18n.js:313:29)
    at Object.callWrap (/home/ubuntu/nunjucksapp/node_modules/nunjucks/src/runtime.js:227:16)
    at root [as rootRenderFunc] (eval at <anonymous> (/home/ubuntu/nunjucksapp/node_modules/nunjucks/src/environment.js:420:24), <anonymous>:11:66)
    at null.<anonymous> (/home/ubuntu/nunjucksapp/node_modules/nunjucks/src/environment.js:357:18)
    at Object.exports.withPrettyErrors (/home/ubuntu/nunjucksapp/node_modules/nunjucks/src/lib.js:22:16)
    at Obj.extend.render (/home/ubuntu/nunjucksapp/node_modules/nunjucks/src/environment.js:344:20)
    at /home/ubuntu/nunjucksapp/node_modules/nunjucks/src/environment.js:219:22

I realize I should have used the Mozilla i18n library (hindsight is always 20/20). However this seems like a bug Nunjucks should work out anyway.

**Comment by KishCom** [comment]
OMG. How embarrassing. Problem was else where in my code. Nunjucks rocks! Thanks guys.

**Comment by jlongster** [comment]
That's why I give issues a little while before responding :)
