### ISSUE TITLE
Raw is broken, gets confused with "fake" variable declarations

### ISSUE THREAD

**Issue by AaronO** [mozilla/nunjucks#447]
Raw blocks break when there's something that looks like a variable declaration but isn't, for example `{{ x }` (it opens like a variable but doesn't end like one).

### Sample

```html
{% raw %}
<code>
{{ i_am_a_dumb_variable }}

{{ i_am_an_imposter_i_kill_nunjucks }
</code>
{% endraw %}
```

### Stacktrace

```
/Users/aaron/git/nunjucks/src/environment.js:425
            else throw err;
                       ^
Template render error: (/Users/aaron/git/nunjucks/tests/raw.html)
  expected endraw, got end of file
    at Object.exports.prettifyError (/Users/aaron/git/nunjucks/src/lib.js:34:15)
    at Obj.extend.render (/Users/aaron/git/nunjucks/src/environment.js:423:27)
    at /Users/aaron/git/nunjucks/src/environment.js:270:35
    at createTemplate (/Users/aaron/git/nunjucks/src/environment.js:194:25)
    at handle (/Users/aaron/git/nunjucks/src/environment.js:206:25)
    at /Users/aaron/git/nunjucks/src/environment.js:223:21
    at next (/Users/aaron/git/nunjucks/src/lib.js:198:13)
    at Object.exports.asyncIter (/Users/aaron/git/nunjucks/src/lib.js:205:5)
    at Obj.extend.getTemplate (/Users/aaron/git/nunjucks/src/environment.js:202:17)
    at Obj.extend.render (/Users/aaron/git/nunjucks/src/environment.js:262:14)
```

This obviously isn't the expected behavior. I'm looking into the parser's raw parsing, but maybe someone more familiar with the codebase knows precisely where it messes up.

**Comment by AaronO** [comment]
After digging a little bit further, it becomes obvious that the tokenization of both expressions is very different

`{% raw %}{{ x }}{% endraw %}` becomes

```
{ type: 'variable-start', value: '{{', lineno: 0, colno: 5 }
{ type: 'whitespace', value: ' ', lineno: 0, colno: 5 }
{ type: 'symbol', value: 'x', lineno: 0, colno: 6 }
{ type: 'whitespace', value: ' ', lineno: 0, colno: 7 }
{ type: 'variable-end', value: '}}', lineno: 0, colno: 8 }
{ type: 'block-start', value: '{%', lineno: 0, colno: 8 }
```

whereas `{% raw %}{{ x }{% endraw %}` becomes:

```
{ type: 'variable-start', value: '{{', lineno: 0, colno: 5 }
{ type: 'whitespace', value: ' ', lineno: 0, colno: 5 }
{ type: 'symbol', value: 'x', lineno: 0, colno: 6 }
{ type: 'whitespace', value: ' ', lineno: 0, colno: 7 }
{ type: 'right-curly', value: '}', lineno: 0, colno: 8 }
{ type: 'left-curly', value: '{', lineno: 0, colno: 9 }
{ type: 'operator', value: '%', lineno: 0, colno: 10 }
{ type: 'whitespace', value: ' ', lineno: 0, colno: 11 }
{ type: 'symbol', value: 'endraw', lineno: 0, colno: 12 }
{ type: 'whitespace', value: ' ', lineno: 0, colno: 18 }
{ type: 'block-end', value: '%}', lineno: 0, colno: 19 }
```

Maybe this should be fixed at the `tokenizer` level rather than at the `parser` level
