### ISSUE TITLE
weird crash using express.js + nunjucks as templating engine

### ISSUE THREAD

**Issue by mrgamer** [mozilla/nunjucks#469]
I'm writing this issue for posterity, I commited the crime of not being thorough reading the documentation and used `nunjucks.render` as a template engine for express.js

Like this:
```javascript
// DO NOT DO THIS PLEASE
var app = express();
app.engine('j2', nunjucks.render);
app.set('view engine', 'j2');
```

It all works wonders, although when the service gets started via a very simple upstart script (It's appended), the express.js server crashes on **every** page render (`res.render('something')`).

This is the weird error:
```javascript
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: watch EACCES
    at exports._errnoException (util.js:846:11)
    at FSWatcher.start (fs.js:1228:11)
    at Object.fs.watch (fs.js:1254:11)
    at createFsWatchInstance (/srv/backend/089ebb0/node_modules/nunjucks/node_modules/chokidar/lib/nodefs-handler.js:24:15)
    at setFsWatchListener (/srv/backend/089ebb0/node_modules/nunjucks/node_modules/chokidar/lib/nodefs-handler.js:47:19)
    at EventEmitter.NodeFsHandler._watchWithNodeFs (/srv/backend/089ebb0/node_modules/nunjucks/node_modules/chokidar/lib/nodefs-handler.js:177:15)
    at EventEmitter.NodeFsHandler._handleDir (/srv/backend/089ebb0/node_modules/nunjucks/node_modules/chokidar/lib/nodefs-handler.js:301:8)
    at EventEmitter.<anonymous> (/srv/backend/089ebb0/node_modules/nunjucks/node_modules/chokidar/lib/nodefs-handler.js:342:12)
    at FSReqWrap.oncomplete (fs.js:78:15)
```

Maybe it's bound to the auto-watching of files, because if I correctly configure nunjucks using:
```javascript
var app = express();
nunjucks.configure({
  watch: true,
  express: app
});
app.set('view engine', 'j2');
```
It just crashes from at the start.

**WEIRD PART** this crash only happens when run via upstart, normal shell works wonders (both on windows and in linux)

Upstart script used for reference:
```upstart
description "Crashing Production Server"
author      "mrgamer - <mister.gamer@gmail.com>"

start on filesystem or runlevel [2345]
stop on shutdown

# Automatically Respawn:
respawn
respawn limit 3 5

setuid www-data
setgid adm

env NODE_ENV="production"
env PORT="8001"
env HOSTNAME="127.0.0.1"
script
  exec /usr/bin/node /srv/backend/089ebb0/index.js >> /var/log/node/access.log 2>> /var/log/node/error.log
end script

pre-start script
  echo "[`date`] node.js listening on http://$HOSTNAME:$PORT/" >> /var/log/node/access.log
end script

pre-stop script
  echo "[`date`] node.js stopping" >> /var/log/node/access.log
end script
```

**Comment by waynebloss** [comment]
@mrgamer Take a look at this issue and see if that helps you solve it - [chokidar - Handle EACCES gracefully](https://github.com/paulmillr/chokidar/issues/266).

A maintainer responds "The error is thrown because you didn't attach a listener to the error event on your chokidar instance."

**Comment by jlongster** [comment]
Good call @waynebloss, I just added an error handler. Hopefully it helps out in places like this.
