### ISSUE TITLE
Templates in sub-folders ?

### ISSUE THREAD

**Issue by gahula** [mozilla/nunjucks#470]
// nunjucks defaults
nunjucks.configure('views', {
    autoescape: true,
    express: app
});

//render html
res.render('map/index-view.html', context);

//folder hierarchy
views
---map
   -------index-view.html (has {% extends 'layout-view.html' %} inside)
   -------layout-view.html
---people
---places

//Issue 1
HTML files be in sub-folders ?

_____________________________

[Error: template not found: layout-view.html]
Error: template not found: index-view.html
    at null.<anonymous> (/home/username/webapps/app/node_modules/nunjucks/src/environment.js:175:31)
    at next /home/username/webapps/app/node_modules/nunjucks/src/lib.js:203:13)
    at handle (/home/username/webapps/app/node_modules/nunjucks/src/environment.js:157:25)
    at /home/username/webapps/app/node_modules/nunjucks/src/environment.js:171:21
    at next (/home/username/webapps/app/node_modules/nunjucks/src/lib.js:200:13)
    at Object.exports.asyncIter (/home/username/webapps/app/node_modules/nunjucks/src/lib.js:207:5)
    at Obj.extend.getTemplate (/home/username/webapps/app/node_modules/nunjucks/src/environment.js:150:17)
    at root [as rootRenderFunc] (eval at <anonymous> (/home/username/webapps/app/node_modules/nunjucks/src/environment.js:450:24), <anonymous>:7:5)
    at null.<anonymous> (/home/username/webapps/app/node_modules/nunjucks/src/environment.js:387:18)
    at Object.exports.withPrettyErrors (/home/username/webapps/app/node_modules/nunjucks/src/lib.js:24:16)
    at Obj.extend.render (/home/username/webapps/app/node_modules/nunjucks/src/environment.js:374:20)
    at /home/username/webapps/app/node_modules/nunjucks/src/environment.js:243:22
    at null.<anonymous> (/home/username/webapps/app/node_modules/nunjucks/src/environment.js:192:25)
    at handle (/home/username/webapps/app/node_modules/nunjucks/src/environment.js:154:25)
    at /home/username/webapps/app/node_modules/nunjucks/src/environment.js:171:21
    at next (/home/username/webapps/app/node_modules/nunjucks/src/lib.js:200:13)
GET /map 500 26.619 ms - -

**Comment by waynebloss** [comment]
In index-view.html try changing it to say `{% extends './layout-view.html' %}`.
