### ISSUE TITLE
Filter tag throw error if starting with condition

### ISSUE THREAD

**Issue by SamyPesse** [mozilla/nunjucks#489]
This test is failing:

```js
equal('{% filter title %}{% if a %}a{% else %}b{% endif %}{% endfilter %}', 'b');
```

with:

```
Template render error: (unknown path)
    TypeError: Cannot call method 'concat' of undefined
      at Object.exports.prettifyError (src/lib.js:9:1149)
      at Obj.extend.render (src/environment.js:9:20861)
      at render (tests/util.js:91:22)
      at equal (tests/util.js:35:19)
      at Context.<anonymous> (tests/compiler.js:1102:13)
```

**Comment by jlongster** [comment]
You're totally right. Unfortunately `filter` only works with simple output right now. I thought it would be pretty easy to fix but I'm actually finding it hard to see. This would be a good fun bug for anyone wanting to work on the compiler.

**Comment by Demon-Sheriff** [comment]
@SamyPesse  I would like to work on this issue
