### ISSUE TITLE
Switching from swig, but getting errors with imported macros

### ISSUE THREAD

**Issue by curiousdannii** [mozilla/nunjucks#553]
([I posted on the Google Group, but haven't had a reply](https://groups.google.com/forum/?fromgroups#!topic/nunjucks/0tr3Q0xH-Ew))

I'm trying to switch from swig to nunjucks, but I'm getting errors when I try to use imported macros.

My macros are defined in https://raw.githubusercontent.com/i7/i7el/master/web/views/macros.html

And an example of when they're used is in https://raw.githubusercontent.com/i7/i7el/master/web/views/index.html

The following error is shown:

```
Template render error: (/home/dannii/i7el/web/views/index.html) [Line 28, Column 19]
  Error: Unable to call `macros["icon"]`, which is undefined or falsey
    at Object.exports.prettifyError (/home/dannii/i7el/node_modules/nunjucks/src/lib.js:34:15)
    at /home/dannii/i7el/node_modules/nunjucks/src/environment.js:462:31
    at eval (eval at <anonymous> (/home/dannii/i7el/node_modules/nunjucks/src/environment.js:537:24), <anonymous>:47:11)
    at b_content (eval at <anonymous> (/home/dannii/i7el/node_modules/nunjucks/src/environment.js:537:24), <anonymous>:94:3)
    at eval (eval at <anonymous> (/home/dannii/i7el/node_modules/nunjucks/src/environment.js:537:24), <anonymous>:46:86)
    at b_head (eval at <anonymous> (/home/dannii/i7el/node_modules/nunjucks/src/environment.js:537:24), <anonymous>:76:1)
    at eval (eval at <anonymous> (/home/dannii/i7el/node_modules/nunjucks/src/environment.js:537:24), <anonymous>:18:83)
    at b_title (eval at <anonymous> (/home/dannii/i7el/node_modules/nunjucks/src/environment.js:537:24), <anonymous>:65:1)
    at eval (eval at <anonymous> (/home/dannii/i7el/node_modules/nunjucks/src/environment.js:537:24), <anonymous>:14:84)
    at /home/dannii/i7el/node_modules/nunjucks/src/environment.js:513:33
    at root [as rootRenderFunc] (eval at <anonymous> (/home/dannii/i7el/node_modules/nunjucks/src/environment.js:537:24), <anonymous>:143:1)
    at Obj.extend.getExported (/home/dannii/i7el/node_modules/nunjucks/src/environment.js:508:14)
    at eval (eval at <anonymous> (/home/dannii/i7el/node_modules/nunjucks/src/environment.js:537:24), <anonymous>:10:5)
    at Obj.extend.getTemplate (/home/dannii/i7el/node_modules/nunjucks/src/environment.js:185:17)
    at root [as rootRenderFunc] (eval at <anonymous> (/home/dannii/i7el/node_modules/nunjucks/src/environment.js:537:24), <anonymous>:8:5)
    at eval (eval at <anonymous> (/home/dannii/i7el/node_modules/nunjucks/src/environment.js:537:24), <anonymous>:26:16)
```

Any ideas what I'm doing wrong?

**Comment by carljm** [comment]
Responded on the mailing list.
