### ISSUE TITLE
Including template many times in forloop causes a `RangeError: Maximum call stack size exceeded`

### ISSUE THREAD

**Issue by hanamura** [mozilla/nunjucks#643]
It may depend on an environment how many items matter, but using `include` many times in forloop causes a RangeError.

## Steps to reproduce

JavaScript code:

- https://github.com/hanamura/nunjucks-include-range-error/blob/master/index.js

Templates:

- https://github.com/hanamura/nunjucks-include-range-error/blob/master/template/problem-a.html
- https://github.com/hanamura/nunjucks-include-range-error/blob/master/template/problem-b.html

Render template with 10,000 items:

```sh
node index.js 10000 problem-a.html
```

Expect to proceed without errors, but actually RangeError is caused:

```
Template render error: (/home/travis/build/hanamura/nunjucks-include-range-error/template/problem-a.html)
  Template render error: (/home/travis/build/hanamura/nunjucks-include-range-error/template/problem-a.html)
  Template render error: (/home/travis/build/hanamura/nunjucks-include-range-error/template/problem-b.html)
  Template render error: (/home/travis/build/hanamura/nunjucks-include-range-error/template/problem-a.html)

...

  RangeError: Maximum call stack size exceeded
    at Object.exports.prettifyError (/home/travis/build/hanamura/nunjucks-include-range-error/node_modules/nunjucks/src/lib.js:34:15)
    at /home/travis/build/hanamura/nunjucks-include-range-error/node_modules/nunjucks/src/environment.js:485:31
    at root [as rootRenderFunc] (eval at <anonymous> (/home/travis/build/hanamura/nunjucks-include-range-error/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:39:3)
    at Obj.extend.render (/home/travis/build/hanamura/nunjucks-include-range-error/node_modules/nunjucks/src/environment.js:478:15)
    at /home/travis/build/hanamura/nunjucks-include-range-error/node_modules/nunjucks/src/environment.js:311:35
    at createTemplate (/home/travis/build/hanamura/nunjucks-include-range-error/node_modules/nunjucks/src/environment.js:234:25)
    at handle (/home/travis/build/hanamura/nunjucks-include-range-error/node_modules/nunjucks/src/environment.js:249:25)
    at /home/travis/build/hanamura/nunjucks-include-range-error/node_modules/nunjucks/src/environment.js:263:21
    at next (/home/travis/build/hanamura/nunjucks-include-range-error/node_modules/nunjucks/src/lib.js:207:13)
    at Object.exports.asyncIter (/home/travis/build/hanamura/nunjucks-include-range-error/node_modules/nunjucks/src/lib.js:214:5)
```

## Workaround

Avoid using `include` and write templates inline.

Template:

- https://github.com/hanamura/nunjucks-include-range-error/blob/master/template/workaround-a.html

Render:

```sh
node index.js 10000 workaround-a.html
```

---

This is an example repository:

- https://github.com/hanamura/nunjucks-include-range-error

```sh
git clone https://github.com/hanamura/nunjucks-include-range-error.git
cd nunjucks-include-range-error
npm install
npm test
```

This is Travis CI URL that represent it:

- https://travis-ci.org/hanamura/nunjucks-include-range-error/builds/103783131

**Comment by carljm** [comment]
Thanks for the report! I'll be honest - I think this may be complex to fix, and I don't personally have any intention to work on it. I would gladly review and accept a pull request that fixes it, however!

**Comment by hydiak** [comment]
There is no such problem with actual version of nunjucks:
https://github.com/hanamura/nunjucks-include-range-error/pull/1

But [this](https://github.com/mozilla/nunjucks/issues/749) problem is still exists.
I'll try to make reproducible test case.
