### ISSUE TITLE
Detected use of sync API

### ISSUE THREAD

**Issue by pkolt** [mozilla/nunjucks#726]
Synchronous calls occur when rendering the template.

template: `views/index.html`
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test page</title>
</head>
<body>
    <h1>Test page</h1>
</body>
</html>
```

application: `app.js`
```javascript
var express = require('express');
var nunjucks = require('nunjucks');

var app = express();


nunjucks.configure(__dirname + '/views', {
    express: app
});

app.get('/', function(req, res) {
    res.render('index.html');
});

app.listen(3000);
```

run:

```bash
$ node --trace-sync-io app.js
```

out:
```text
WARNING: Detected use of sync API
    at fs.existsSync (fs.js:223:13)
    at Loader.extend.getSource (/home/pkolt/Projects/nunjucks-async/node_modules/nunjucks/src/node-loaders.js:64:45)
    at /home/pkolt/Projects/nunjucks-async/node_modules/nunjucks/src/environment.js:263:41
    at next (/home/pkolt/Projects/nunjucks-async/node_modules/nunjucks/src/lib.js:207:13)
    at exports.asyncIter (/home/pkolt/Projects/nunjucks-async/node_modules/nunjucks/src/lib.js:214:5)
    at Obj.extend.getTemplate (/home/pkolt/Projects/nunjucks-async/node_modules/nunjucks/src/environment.js:242:17)
    at Obj.extend.render (/home/pkolt/Projects/nunjucks-async/node_modules/nunjucks/src/environment.js:303:14)
    at NunjucksView.render (/home/pkolt/Projects/nunjucks-async/node_modules/nunjucks/src/environment.js:284:15)
    at tryRender (/home/pkolt/Projects/nunjucks-async/node_modules/express/lib/application.js:639:10)
WARNING: Detected use of sync API
    at fs.openSync (fs.js:584:18)
    at fs.readFileSync (fs.js:431:33)
    at Loader.extend.getSource (/home/pkolt/Projects/nunjucks-async/node_modules/nunjucks/src/node-loaders.js:76:26)
    at /home/pkolt/Projects/nunjucks-async/node_modules/nunjucks/src/environment.js:263:41
    at next (/home/pkolt/Projects/nunjucks-async/node_modules/nunjucks/src/lib.js:207:13)
    at exports.asyncIter (/home/pkolt/Projects/nunjucks-async/node_modules/nunjucks/src/lib.js:214:5)
    at Obj.extend.getTemplate (/home/pkolt/Projects/nunjucks-async/node_modules/nunjucks/src/environment.js:242:17)
    at Obj.extend.render (/home/pkolt/Projects/nunjucks-async/node_modules/nunjucks/src/environment.js:303:14)
    at NunjucksView.render (/home/pkolt/Projects/nunjucks-async/node_modules/nunjucks/src/environment.js:284:15)
WARNING: Detected use of sync API
    at fs.fstatSync (fs.js:882:18)
    at fs.readFileSync (fs.js:437:13)
    at Loader.extend.getSource (/home/pkolt/Projects/nunjucks-async/node_modules/nunjucks/src/node-loaders.js:76:26)
    at /home/pkolt/Projects/nunjucks-async/node_modules/nunjucks/src/environment.js:263:41
    at next (/home/pkolt/Projects/nunjucks-async/node_modules/nunjucks/src/lib.js:207:13)
    at exports.asyncIter (/home/pkolt/Projects/nunjucks-async/node_modules/nunjucks/src/lib.js:214:5)
    at Obj.extend.getTemplate (/home/pkolt/Projects/nunjucks-async/node_modules/nunjucks/src/environment.js:242:17)
    at Obj.extend.render (/home/pkolt/Projects/nunjucks-async/node_modules/nunjucks/src/environment.js:303:14)
    at NunjucksView.render (/home/pkolt/Projects/nunjucks-async/node_modules/nunjucks/src/environment.js:284:15)
WARNING: Detected use of sync API
    at fs.readSync (fs.js:651:19)
    at fs.readFileSync (fs.js:467:24)
    at Loader.extend.getSource (/home/pkolt/Projects/nunjucks-async/node_modules/nunjucks/src/node-loaders.js:76:26)
    at /home/pkolt/Projects/nunjucks-async/node_modules/nunjucks/src/environment.js:263:41
    at next (/home/pkolt/Projects/nunjucks-async/node_modules/nunjucks/src/lib.js:207:13)
    at exports.asyncIter (/home/pkolt/Projects/nunjucks-async/node_modules/nunjucks/src/lib.js:214:5)
    at Obj.extend.getTemplate (/home/pkolt/Projects/nunjucks-async/node_modules/nunjucks/src/environment.js:242:17)
    at Obj.extend.render (/home/pkolt/Projects/nunjucks-async/node_modules/nunjucks/src/environment.js:303:14)
    at NunjucksView.render (/home/pkolt/Projects/nunjucks-async/node_modules/nunjucks/src/environment.js:284:15)
WARNING: Detected use of sync API
    at fs.closeSync (fs.js:553:18)
    at /home/pkolt/Projects/nunjucks-async/node_modules/graceful-fs/graceful-fs.js:51:27
    at fs.readFileSync (fs.js:487:8)
    at Loader.extend.getSource (/home/pkolt/Projects/nunjucks-async/node_modules/nunjucks/src/node-loaders.js:76:26)
    at /home/pkolt/Projects/nunjucks-async/node_modules/nunjucks/src/environment.js:263:41
    at next (/home/pkolt/Projects/nunjucks-async/node_modules/nunjucks/src/lib.js:207:13)
    at exports.asyncIter (/home/pkolt/Projects/nunjucks-async/node_modules/nunjucks/src/lib.js:214:5)
    at Obj.extend.getTemplate (/home/pkolt/Projects/nunjucks-async/node_modules/nunjucks/src/environment.js:242:17)
    at Obj.extend.render (/home/pkolt/Projects/nunjucks-async/node_modules/nunjucks/src/environment.js:303:14)
```
I use:
`nodejs 5.10.1`
`express 4.13.4`
`nunjucks 2.4.1`

I do not want to use synchronous calls. How to fix it?

**Comment by carljm** [comment]
All of the calls you list are coming from the filesystem template loader, which is a sync loader. If your eventual target is browser use, just precompile your templates and you won't be using that loader anymore. If your eventual target is server-side use from Node, you could write your own async filesystem loader. For API details, see the "Asynchronous" section of the "Writing a Loader" docs: http://mozilla.github.io/nunjucks/api.html#writing-a-loader (and you could refer to the source of the existing `FilesystemLoader` for details that wouldn't need to change with the sync/async change).
