### ISSUE TITLE
customer tags seems not support blocks tag

### ISSUE THREAD

**Issue by ErosZy** [mozilla/nunjucks#932]
I write a customer extension, but i found customer tags not support blocks tag.
```html
{% html lange='zh-cn' %}
  {% block css %}{% endblock %}
{% endhtml %}
```
it throw error
```html
 Template render error: (D:\work\nord-nunjucks\test\views\parent.tpl)
  Error: unknown block "css"
      at Object.exports.prettifyError (node_modules\.3.0.0@nunjucks\src\lib.js:34:15)
      at node_modules\.3.0.0@nunjucks\src\environment.js:489:31
      at root [as rootRenderFunc] (eval at <anonymous> (node_modules\.3.0.0@nunjucks\src\environment.js:568:24), <anonymous>:77:3)
      at Obj.extend.render (node_modules\.3.0.0@nunjucks\src\environment.js:482:15)
      at node_modules\.3.0.0@nunjucks\src\environment.js:313:35
      at createTemplate (node_modules\.3.0.0@nunjucks\src\environment.js:235:25)
      at handle (node_modules\.3.0.0@nunjucks\src\environment.js:250:25)
      at node_modules\.3.0.0@nunjucks\src\environment.js:264:21
      at next (node_modules\.3.0.0@nunjucks\src\lib.js:207:13)
      at Object.exports.asyncIter (node_modules\.3.0.0@nunjucks\src\lib.js:214:5)
      at Obj.extend.getTemplate (node_modules\.3.0.0@nunjucks\src\environment.js:243:17)
      at Obj.extend.render (node_modules\.3.0.0@nunjucks\src\environment.js:305:14)
      at Context.<anonymous> (test\all.js:6:23)
      at callFn (node_modules\.3.2.0@mocha\lib\runnable.js:345:21)
      at Test.Runnable.run (node_modules\.3.2.0@mocha\lib\runnable.js:337:7)
      at Runner.runTest (node_modules\.3.2.0@mocha\lib\runner.js:444:10)
      at node_modules\.3.2.0@mocha\lib\runner.js:550:12
      at next (node_modules\.3.2.0@mocha\lib\runner.js:361:14)
      at node_modules\.3.2.0@mocha\lib\runner.js:371:7
      at next (node_modules\.3.2.0@mocha\lib\runner.js:295:14)
      at Immediate._onImmediate (node_modules\.3.2.0@mocha\lib\runner.js:339:5)
```

my customer tag code like this:
```javascript
/**
 * {% html lang='zh-cn' %}
 *      {% head %}
 *          <title>{{title}}</title>
 *      {% endhead %}
 *      {% body %}
 *          something else in there
 *      {% endbody %}
 * {% endhtml %}
 *
 */

var nunjucks = require('nunjucks');
var _ = require("underscore");

function HtmlExtension() {
    this.tags = ["html"];

    this.parse = function (parser, nodes) {
        var tok = parser.nextToken();
        var attrs = parser.parseSignature(null, true);
        parser.advanceAfterBlockEnd(tok.value);

        var body = parser.parseUntilBlocks('endhtml');
        parser.advanceAfterBlockEnd();

        return new nodes.CallExtension(this, 'run', attrs, [body]);
    };

    this.run = function (context) {
        return '';

        var args = _.toArray(arguments);
        var body = args.pop();
        args = args.splice(1);
        args = _.flatten(_.compact(args));
        args = _.map(args, function (val) {
            var items = _.map(val, function (item, key) {
                if (key !== '__keywords') {
                    return key + '="' + item + '"';
                }
            });
            return _.compact(items).join(' ');
        });

        var code = '<!DOCTYPE html><html ' + args.join(' ') + '>' + body() + '</html>';
        return new nunjucks.runtime.SafeString(code);
    }
}

module.exports = HtmlExtension;
```

have some solution to solve this problem, thanks.

**Comment by ogonkov** [comment]
@ErosZy did you fix this issue?

**Comment by ErosZy** [comment]
@ogonkov no, i create a extension which called my-block(or something), its code copied from nunjucks block source code.
